### ISSUE TITLE
npm package is not working

### ISSUE THREAD

**Issue by fennabe** [romlm/native-sound-mixer#2]
First of all, thank you for the work you have done. 

I'm not sure if I'm doing something wrong or not but I don't get this package to work.
I'm using this package inside electron (with React) so I should be able to use native node.js packages in the main process. When I add the package with yarn, the folder _/node_modules/native-sound-mixer/dist_ does only contain SoundMixer.node, no javascript files.

I'm unable to import anything because this dist folder is empty. What am i missing here?

**Comment by romlm** [comment]
Thanks for reporting, it shall be fixed now. I forgot to include the `tsconfig.json` file and `build` script wasn't properly started after install. It shall be working all fine now. Updated npm package too

**Comment by romlm** [comment]
just note that you have to install `node-addon-api` before installing the package

**Comment by romlm** [comment]
Update: now, package can be used for windows after `npm install native-sound-mixer` with version `>=3.0.5`
